name: api deploy

on:
  workflow_call:
    inputs:
      environment:
        required: true
        default: "dev"
        type: string

jobs:
  run-migrations:
    runs-on: ubuntu-latest
    steps:
      - name: Run migration task
        run: |
          echo "${{ inputs.environment }}

