name: api deploy

on:
  workflow_call:
    inputs:
      environment:
        required: true
        default: "dev"
        type: string

jobs:
  run-deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Run deployment
        run: |
          echo "${{ inputs.environment }}"
